config/routes.rb
SummerOfProject::Application.routes.draw do

  get "admin/index"

  get "ogrenci/index"
  match "admin/groups" => "admin#groups"
  match "admin/create_groups" => "admin#creategroup"
  resources :sessions
  resources :projes

  get "login" => "sessions#new", as: "login"
  get "logout" => "sessions#destroy", as: "logout"

  match "ogrenci/index" => "ogrenci#selectproje"
  match "ogrenci/index" => "ogrenci#rapor"
  root to: 'sessions#new'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.role? :ogrenci
      can :read, Proje
    end

    if user.role? :gyonetici
      can :read, Proje
    end

    if user.role? :hoca
      can :manage, Proje, :user_id => user.id
      can :read, Proje
    end

    if user.role? :admin
      can :manage, Proje
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :proje_id
  has_many :user
  has_one :proje
end

app/models/gyonetici.rb
class Gyonetici < User
end

app/models/hoca.rb
class Hoca < User
end

app/models/ogrenci.rb
class Ogrenci < User
end

app/models/proje.rb
class Proje < ActiveRecord::Base
  attr_accessible :title, :content, :group_id
  has_one :group
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :username, :ad, :soyad, :email, :tel, :okulno, :password, :password_confirmation, :role, :type, :group_id

  ROLES = %w[ogrenci gyonetici hoca admin]

  def role?(base_role)
     ROLES.index(base_role.to_s) <= ROLES.index(role)
  end
end

app/controllers/admin_controller.rb
#encoding: utf-8
class AdminController < ApplicationController
  before_filter :filter

  def filter
    redirect_to '/login' unless session[:user_id]
  end

  def index
    @ogrenci = Ogrenci.all.reject { |p| p.group_id? }
  end

  def creategroup
    if params[:ogrenci_ids]
      @groups = Group.create(name:params[:name])

      @ogrenci = Ogrenci.find(params[:ogrenci_ids])
      @ogrenci.each do |ogrenci|
        @ogrenci = Ogrenci.update(params[:ogrenci_ids].shift, group_id:Group.last.id)
      end

      if @ogrenci
        redirect_to '/admin/groups', notice: "Başarılı bir şekilde grup oluşturulmuştur."
      else
        redirect_to admin_index_path, notice: "Grup oluturulamadı."
      end
    else
      redirect_to admin_index_path, notice: "Grup oluşturulamadı. Lütfen öğrenci seçeneklerini işaretleyiniz."
    end
  end

  def groups
    @groups = Group.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  before_filter :set_locale

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end
end

app/controllers/ogrenci_controller.rb
#encoding: utf-8
class OgrenciController < ApplicationController
  before_filter :filter

  def filter
    redirect_to '/login' unless session[:user_id]
  end

  def index
    @groups = Group.find(current_user.group_id)
    if @groups.proje_id
      @proje = Proje.find(@groups.proje_id)
    else
      #
    end
  end

  def selectproje
    @groups =Group.find(current_user.group_id)
    if params[:proje_ids].length > 1
      redirect_to '/projes', notice:"Lütfen sadece 1 tane proje seçiniz."
    else
      @ogrenci = Ogrenci.find(current_user.id)
      @groups = Group.update(current_user.group_id, proje_id:params[:proje_ids].join)
      @proje = Proje.update(params[:proje_ids].join, group_id:current_user.group_id)
      if @groups
        redirect_to '/ogrenci/index', notice:"Proje seçimi tamamlandı."
      else
        redirect_to '/projes', notice:"Proje seçimi başarısız."
      end
    end
  end

  def rapor
     @groups = Group.find(current_user.group_id)
    if params[:rapor]
      directory = "public/data"
      path = File.join(directory, name)
      @groups.rapor = File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
      @groups.save
      if @groups
        redirect_to '/ogrenci/rapor', notice:"Rapor Eklendi"
      else
        redirect_to '/ogrenci/index', notice:"Tekrar deneyiniz."
      end
    end
  end

end

app/controllers/projes_controller.rb
#encoding: utf-8
class ProjesController < ApplicationController
  load_and_authorize_resource
  # GET /projes
  # GET /projes.json
  def index
    @projes = Proje.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projes }
    end
  end

  # GET /projes/1
  # GET /projes/1.json
  def show
    @proje = Proje.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proje }
    end
  end

  # GET /projes/new
  # GET /projes/new.json
  def new
    @proje = Proje.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proje }
    end
  end

  # GET /projes/1/edit
  def edit
    @proje = Proje.find(params[:id])
  end

  # POST /projes
  # POST /projes.json
  def create
    @proje = Proje.new(params[:proje])
    @proje.user = current_user

    respond_to do |format|
      if @proje.save
        format.html { redirect_to @proje, notice: 'Proje was successfully created.' }
        format.json { render json: @proje, status: :created, location: @proje }
      else
        format.html { render action: "new" }
        format.json { render json: @proje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projes/1
  # PUT /projes/1.json
  def update
    @proje = Proje.find(params[:id])
    @proje.user = current_user

    respond_to do |format|
      if @proje.update_attributes(params[:proje])
        format.html { redirect_to @proje, notice: 'Proje was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projes/1
  # DELETE /projes/1.json
  def destroy
    @proje = Proje.find(params[:id])
    @proje.destroy

    respond_to do |format|
      format.html { redirect_to projes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      case user.type
      when "Ogrenci"
        redirect_to ogrenci_index_path
      when "Admin"
        redirect_to admin_index_path
      else
        redirect_to projes_path
      end
    else
      flash.now.alert = "Invalid username or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ogrenci_helper.rb
module OgrenciHelper
end

app/helpers/projes_helper.rb
module ProjesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/creategroup.html.erb
TODO

<%= params[:ogrenci_ids] %>
<%= params[:ogrenci] %>
<%= @group.user %>

app/views/admin/groups.html.erb
<table class="table table-bordered">
  <tr>
    <th>Grup ID</th>
    <th>Grup Adı</th>
    <th>Grup Üyeleri</th>
    <th></th>
  </tr>
<% @groups.each do |g| %>
  <tr>
    <td><%= g.id %></td>
    <td><%= g.name %></td>
    <td><% g.user.each do |i| %>
                <%= i.id %>
                <%= i.ad %>
                <%= i.soyad %><br />
	<% end %></td>
<% end %>
</table>

app/views/admin/index.html.erb
<div class="btn-group dropdown">
  <button class="btn">Admin Menü</button>
  <button class="btn dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><a href="/projes">Projeler</a></li>
    <li><a href="/admin/groups">Gruplar</a></li>
    <li><a href="/projes">Proje Oluştur</a></li>
</ul>
</div>  

<br>          
    
Öğrenci listesi

<table>
  <tr>
    <th></th>
    <th>No</th>
    <th>Ad</th>
    <th>Soyad</th>
    <th>Email</th>
    <th></th>
  </tr>
<%= form_tag( controller:"admin", action:"creategroup") do %>
<% @ogrenci.each do |ogrenci| %>
  <tr>
    <td><%= check_box_tag "ogrenci_ids[]", ogrenci.id %></td>
    <td><%= ogrenci.okulno %></td>
    <td><%= ogrenci.ad %></td>
    <td><%= ogrenci.soyad %></td>
    <td><%= ogrenci.email %></td>
  </tr>
<% end %>
<%= text_field_tag(:name) %>
<%= submit_tag "Oluştur" %>
</table>
<% end %>

<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t 'welcome.title' %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
   <!-- main-bar -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">Proje Yönetim Sistemi</a>
          <ul class="nav">
         
          

<!-- i18n -->
 
  <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t 'welcome.languages' %><b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><a href="?locale=tr">Türkçe</a></li>
    <li class="divider"></li>
    <li><a href="?locale=en">English</a></li>
    <li><a href="?locale=ru">Русский</a></li>
  </ul>
  </li>
  

</ul>
</div>
</div>
</div>
<p>
     <% if @current_user  %>
      (: WELCOME..  <b><%= @current_user.username %></b> |
      <%= link_to "ÇIKIŞ", logout_url %>
    <% else %>
      Have not logged in..! |
      <%= link_to "GİRİŞ", login_url %>
    <% end %>
  </p>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<%= yield %>
  
    
<!-- footer -->

<div class="navbar navbar-fixed-bottom">
      <div class="navbar-inner">
        <div class="container">
          <ul class="nav">
            <li><a href="/">Summer-of-Project &copy; <%= Time.now.year %> <a></li>
</ul>
</div>
</div>
<!-- /footer -->

</body>
</html>

app/views/ogrenci/index.html.erb
<% if @ogrenci.group_id %>
  <% if  @groups.proje_id %>
	Projeniz:<br />Başlık: <%= @proje.title %><br />
	İçerik:  <%= @proje.content %><br />
	<% if current_user.role == "gyonetici" %>
	  Rapor Ekle:
	  <%= form_tag(controller:"ogrenci", action:"rapor", multipart:true ) do %>
	    <%= file_field_tag 'rapor' %>
	    <%= submit_tag 'Gönder' %>
          <% end %>
	<% end %>
  <% else %>
	Projeleri görmek için aşağıdaki linke tıklayınız:
	<%= link_to 'Proje', projes_path %>
  <% end %>
<% else %>
	Lütfen grup yöneticiniz ile proje seçiniz.
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projes/_form.html.erb
<%= form_for(@proje) do |f| %>
  <% if @proje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proje.errors.count, "error") %> İlgili proje kaydedilemez:</h2>

      <ul>
      <% @proje.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<p>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
</p>
<p>  
<div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
</p>

<p>
  <div class="actions">
    <%= f.submit %>
  </div>
</p>
<% end %>

app/views/projes/edit.html.erb
<h1>Projeyi Düzenle</h1>

<%= render 'form' %>

<%= link_to 'Show', @proje %> |
<%= link_to 'Back', projes_path %>

app/views/projes/index.html.erb
<p></p>
<h2>Proje Listesi</h2>
<p></p>

<table>
  <tr>
    <th>Proje Adı</th>
    <th></th>
    <th></th>
    <th></th>
    <th>Projenin İçeriği</th>
    <th></th>
    <th></th>
  </tr>

<p></p>
<% @projes.each do |proje| %>
  <tr>
    <td><%= proje.title %></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= proje.content %></td>

    <td><%= link_to 'Show', proje %></td> 
    <td></td>
    <% if can? :edit, proje %>
      <td><%= link_to 'Edit', edit_proje_path(proje) %></td>
    <% end %> 
     <td></td>
    <% if can? :destroy, proje %>
     
   <td><%= link_to 'Destroy', proje, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
    <% end %>
    <td></td>
  </tr>
<% end %>
</table>

<br />

<% if can? :create, Proje %>
  <%= link_to 'New Proje', new_proje_path %>
<% end %>

app/views/projes/new.html.erb
<p></p>

<h2>Yeni Proje</h2>

<p></p>


<%= render 'form' %>

<%= link_to '<<-Back', projes_path %>

app/views/projes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Proje Adı:</b>
  <%= @proje.title %>
</p>

<p>
  <b>Projenin İçeriği:</b>
  <%= @proje.content %>
</p>


<% if can? :edit, @proje %>
  <%= link_to 'Edit', edit_proje_path(@proje) %>
<% end %> 
<td>|</td>

<td></td>
<%= link_to '<<-Back', projes_path %>